### ISSUE TITLE
Add possibility to download from other sources

### ISSUE THREAD

**Issue by LaustFaerch** [DHI-GRAS/copernicus_download#12]
VITO has some data lying here: https://www.vito-eodata.be/PDF/datapool/
Could be nice if we could access this data using this script.
I'll try to make a PR.

**Comment by j08lue** [comment]
The `/PDF/datapool` part makes me hope that the site is structured in a similar way, so our crawling method will work. Can you verify, please, that the product sites look the same as on http://land.copernicus.vgt.vito.be/PDF/datapool/?

**Comment by LaustFaerch** [comment]
Site looks the same. I have made a new branch and it should work.
As I guess this code is used for production - maybe we should go over the changes together before merging? My changes are minimal, but you never know if I unknowningly messed up something.

**Comment by j08lue** [comment]
Yes, let's follow the usual flow: 

1. you branch (or fork) and open a pull request
2. I review the PR and make change requests, if necessary
3. You respond to the requests in comments and code
4. I approve and merge the PR
