### ISSUE TITLE
Failing downloads do not raise an exception

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/copernicus_download#5]
https://github.com/DHI-GRAS/vito-download/blob/c857f00a8b5a823d4124f3fecb49fc11a9058a4f/vito_download/download.py#L27-L40

Instead, they leave empty files behind.

The `while` loop with retries is OK, but the `logger.warn` should perhaps rather be an exception that gets raised. And the `shutil.copyfileobj` should come **after** the response length check.

**Comment by dionhaefner** [comment]
> And the shutil.copyfileobj should come after the response length check.

No. `response.raw.tell()` gives you the bytes read from the stream, which is 0 before the `copyfileobj`.

**Comment by j08lue** [comment]
@dionhaefner it makes sense that it does, thanks. Then we just need to make the final `shutil.move` dependent on that the loop finished successfully.
